apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-config
  namespace: dev
data:
  SPRING_PROFILES_ACTIVE: dev
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql.dev.svc.cluster.local:3306/appdb
  SPRING_DATASOURCE_USERNAME: appuser
  SPRING_DATASOURCE_PASSWORD: apppass
  KAFKA_BOOTSTRAP_SERVERS: kafka.dev.svc.cluster.local:9092